apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: apache-airflow-test
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags/latest
    executor = CeleryExecutor
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres/airflow

    [database]
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres/airflow

    [celery]
    broker_url = redis://redis:6379/0
    result_backend = db+postgresql://airflow:airflow@postgres/airflow
    
    flower_url_prefix = /flower
    worker_concurrency = 4
    [webserver]
    web_server_port = 8080
    enable_testing = True