apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi   # ขนาด storage ที่ต้องการ
