apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.3
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: data
              mountPath: /data/loki
            - name: config
              mountPath: /etc/loki
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: loki-data
        - name: config
          configMap:
            name: loki-config
