services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    networks:
      - gitlab-net
    extra_hosts:
      - "gitlab:host-gateway"

networks:
  gitlab-net:
    external: true