apiVersion: v1
kind: Service
metadata:
  name: mydotnetapp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mydotnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Port ที่ใช้เข้าถึงจากภายนอก
