services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_SKIP_UNNECESSARY_SERVICES: "true"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        registry_external_url 'http://registry.gitlab:5005'
        gitlab_rails['registry_enabled'] = true

        ## reduce resource
        sidekiq['concurrency'] = 2
        puma['worker_processes'] = 1
    ports:
      - "8929:8929"   # HTTP (web UI)
      - "2224:22"     # SSH access for repos
      - "5005:5005"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    healthcheck:
      test: ["CMD", "gitlab-ctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 10
    
    networks:
      - gitlab-net

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  gitlab-net:
    external: true