apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: shared-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
    limits:
      storage: 20Gi
