apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shared-db
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31432
