apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: shared-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: medusa
            - name: POSTGRES_PASSWORD
              value: medusa
            - name: POSTGRES_DB
              value: medusa-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
