apiVersion: v1
kind: Service
metadata:
  name: snipeit
  labels:
    app: snipeit
spec:
  type: NodePort  # ใช้ NodePort แทน LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090  # กำหนด NodePort ที่สามารถเข้าถึงได้
  selector:
    app: snipeit
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: snipedb
  labels:
    app: snipedb
spec:
  ports:
    - port: 3306
  selector:
    app: snipe
    tier: snipedb
  clusterIP: None
