apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  # ตัวอย่าง config
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*

    # [OUTPUT]
    #     Name  es
    #     Match *
    #     Host  elasticsearch.logging.svc.cluster.local
    #     Port  9200
    #     Index kubernetes-logs
    #     Type  _doc
    #     Logstash_Format On

    [OUTPUT]
        Name        loki
        Match       *
        Host        loki.logging.svc.cluster.local
        Port        3100
        # Labels      job=fluent-bit
        Labels      job={kubernetes['container_name']}
        auto_kubernetes_labels  on


    # [OUTPUT]
    #     Name kafka
    #     Brokers kafka:9092
    #     Topics kubernetes-logs
    #     Match *

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L