apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shared-db
spec:
  type: NodePort    # เปลี่ยนจาก ClusterIP เป็น NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379   # ระบุ port ที่ต้องการ
