services:
  registry:
    image: registry:2
    container_name: secure-registry
    restart: always
    ports:
      - "5005:5000"
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - ./registry-data:/var/lib/registry
      - ./certs:/certs:ro
    networks:
      - gitlab-net

networks:
  gitlab-net:
    external: true