services:
  registry:
      image: registry:2
      container_name: local-registry
      restart: always
      ports:
        - "5005:5000"
      environment:
        REGISTRY_HTTP_ADDR: 0.0.0.0:5000
        REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://localhost:5005]'
        REGISTRY_STORAGE_DELETE_ENABLED: "true"
      volumes:
        - ./registry-data:/var/lib/registry
      networks:
        - gitlab-net

networks:
  gitlab-net:
    external: true